version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      - run:
          name: Build Docker Image okk
          command: docker build -t devopsfe:latest .
      - run:
          name: Login to Docker Hub
          command: |
            aws ecr get-login-password --region us-east-2  --profile devopsprofile | docker login --username AWS --password-stdin  180432984958.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: Tag Docker Image
          command: docker tag devopsfe:latest 180432984958.dkr.ecr.us-east-2.amazonaws.com/devopsfe:latest
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push 180432984958.dkr.ecr.us-east-2.amazonaws.com/devopsfe:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push
