version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      - run:
          name: Build Docker Image
          command: docker build -t my-react-app:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Tag Docker Image
          command: docker tag my-react-app:latest $DOCKERHUB_USERNAME/my-react-app:latest
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/my-react-app:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push
